# Generated by Django 3.0.5 on 2022-04-10 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Viajes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=30, verbose_name='region')),
                ('origin_coord', models.CharField(max_length=30, verbose_name='origin_coord')),
                ('destination_coord', models.CharField(max_length=30, verbose_name='destination_coord')),
                ('datetime', models.CharField(max_length=30, verbose_name='fecha')),
                ('source', models.CharField(max_length=30, verbose_name='source')),
            ],
        ),
    ]
