# Generated by Django 3.0.5 on 2022-04-10 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filtros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchViajes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='images/')),
                ('description', models.CharField(max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'ArchViajes',
            },
        ),
        migrations.DeleteModel(
            name='Viajes',
        ),
    ]
