# Generated by Django 3.0.5 on 2022-04-10 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filtros', '0003_auto_20220410_2238'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='datos_csv',
            new_name='DatosCsv',
        ),
    ]
